### ISSUE TITLE
Example for changing theme dynamically

### ISSUE THREAD

**Issue by lanocturne** [joaogarin/css-modules-angular2#1]
Hi Joaogarin, thanks again for the awesome demo. My question is on a view that is given a button or dropdown, once triggered, is it right to use css module to change the style globally or locally at app.ts or at a certain component?

**Comment by joaogarin** [comment]
Hello Sorry for the late reply. For some reason I didn't get a notification on this.

I think that if that button is part of the component it should be styled in the component itself and not globally.

But if the button is a generic button then you can for example include it in the app component as global and then you can just reuse that class in other components.
